changelog:
  categories:
    - title: New features 🎉
      labels:
        - feature

    - title: Enhancements 📈
      labels:
        - improvement

    - title: Bug Fixes 🪄
      labels:
        - bugfix

    - title: Dependency Updates 🛠
      labels:
        - dependencies

    - title: Other Changes
      labels:
        - "*"