name: Build Setup
description: Sets up Java, Gradle and Android.

runs:
  using: composite
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: 25

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5